/* eslint-disable */
// Auto-generated by NAPI-RS

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
    // For Node 12+, we can just use process.report.libc
    if (!process.report || typeof process.report.getReport !== 'function') {
        try {
            const lddPath = require('child_process').execSync('which ldd').toString().trim()
            return readFileSync(lddPath, 'utf8').includes('musl')
        } catch (e) {
            return true
        }
    } else {
        const { glibcVersionRuntime } = process.report.getReport().header
        return !glibcVersionRuntime
    }
}

switch (platform) {
    case 'darwin':
        localFileExisted = existsSync(join(__dirname, 'vault-core.darwin-arm64.node'))
        try {
            if (localFileExisted) {
                nativeBinding = require('./vault-core.darwin-arm64.node')
            } else if (arch === 'x64') {
                nativeBinding = require('./vault-core.darwin-x64.node')
            } else if (arch === 'arm64') {
                nativeBinding = require('./vault-core.darwin-arm64.node')
            }
        } catch (e) {
            loadError = e
        }
        break
    case 'win32':
        try {
            nativeBinding = require('./vault-core.win32-x64-msvc.node')
        } catch (e) {
            loadError = e
        }
        break
    case 'linux':
        if (isMusl()) {
            try {
                nativeBinding = require('./vault-core.linux-x64-musl.node')
            } catch (e) {
                loadError = e
            }
        } else {
            try {
                nativeBinding = require('./vault-core.linux-x64-gnu.node')
            } catch (e) {
                loadError = e
            }
        }
        break
    default:
        throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
    if (loadError) {
        throw loadError
    }
    throw new Error(`Failed to load native binding`)
}

const { initDatabase, searchVault, getAllSecrets, getFullSecret, addSecret, deleteSecret, updateSecret, importFromEnvString, exportToEnvString, syncToShell, getEnvvaultFilePath } = nativeBinding

module.exports.initDatabase = initDatabase
module.exports.searchVault = searchVault
module.exports.getAllSecrets = getAllSecrets
module.exports.getFullSecret = getFullSecret
module.exports.addSecret = addSecret
module.exports.deleteSecret = deleteSecret
module.exports.updateSecret = updateSecret
module.exports.importFromEnvString = importFromEnvString
module.exports.exportToEnvString = exportToEnvString
module.exports.syncToShell = syncToShell
module.exports.getEnvvaultFilePath = getEnvvaultFilePath

